version: '3'
services:
  mongodb:
    hostname: mongodb
    image: "mongo"
  user:
    build: app/.
    ports:
      - "8080:8001"
    environment:
      - PORT=8080
      - MONGO_URL="mongodb://mongodb:27017/testDB"
