version: '3'
services:
  mongodb:
    hostname: mongodb
    image: "mongo"
  worker:
    build: worker/.
    environment:
      - MONGO_URL="mongodb://mongodb:27017/testDB"
  user-api:
    build: user-api/.
    ports:
      - "8080:8001"
    environment:
      - PORT=8080
      - MONGO_URL="mongodb://mongodb:27017/testDB"
